
[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
license-file = "LICENSE.md"

[workspace.lints.rust]
missing_docs = "deny"

[workspace.dependencies]
# app-core
belt = { git = "https://github.com/johnbchron/app-core" }
db = { git = "https://github.com/johnbchron/app-core" }
dvf = { git = "https://github.com/johnbchron/app-core" }
kv = { git = "https://github.com/johnbchron/app-core" }
model = { git = "https://github.com/johnbchron/app-core" }

# strictly codegen
serde = { version = "1", features = ["derive"] }

# atomic-ish features
miette = { git = "https://github.com/zkat/miette", default-features = false, features = ["derive"] }
nutype = { version = "0.5" }
thiserror = { version = "2" }
tracing = { version = "0.1", features = ["async-await"] }
ulid = { version = "1.1", features = ["serde"] }

# async
tokio = { version = "1" }
