
[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
license-file = "LICENSE.md"

[workspace.lints.rust]
missing_docs = "deny"

[workspace.dependencies]
# app-core
dvf = { git = "https://github.com/johnbchron/app-core" }
model = { git = "https://github.com/johnbchron/app-core" }

# strictly codegen
serde = { version = "1", features = ["derive"] }

# atomic-ish features
nutype = { version = "0.5" }
ulid = { version = "1.1", features = ["serde"] }
