# fly.toml app configuration file generated for rambit on 2025-07-31T14:50:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rambit'
primary_region = 'dfw'
swap_size_mb = 2048

[build]
  image = 'grid:latest'

[env]
  REDB_STORE_PATH = '/data/rambit-db'

[[mounts]]
  source = 'rambit_db'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
