app = 'rambit'
primary_region = 'dfw'
swap_size_mb = 2048

[build]
image = 'grid:latest'

[env]
REDB_STORE_PATH = '/data/rambit-db'

[[mounts]]
destination = '/data'
initial_size = '1gb'
source = 'rambit_db'

[http_service]
auto_start_machines = false
auto_stop_machines = 'off'
internal_port = 3000
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'
