[package]
name = "mutate-domain"
version = "0.1.0"

edition = "2024"
license-file.workspace = true
publish = false

[dependencies]
models = { path = "../models" }

db.workspace = true

miette.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
