[package]
name = "app"
version = "0.1.0"

edition = "2024"
license-file.workspace = true

[dependencies]
auth-domain = { path = "../auth-domain" }
css-minify-macro = { path = "../css-minify-macro" }
domain = { path = "../domain" }
grid-state = { path = "../grid-state" }
models = { path = "../models" }
# site-paddle = { path = "../site-paddle" }

columbo = { version = "0.2" }
maud = { version = "0.27" }

# async-trait.workspace = true
axum.workspace = true
# futures.workspace = true
miette.workspace = true
# tokio.workspace = true

# serde.workspace = true
tracing.workspace = true

const_base = "0.2"
const_format = "0.2"

[lints]
workspace = true
