[package]
name = "owl"
version = "0.1.0"

edition = "2024"
license-file.workspace = true

[dependencies]
models = { path = "../models" }

belt.workspace = true

miette.workspace = true

nix-nar = { version = "0.3" }

[lints]
workspace = true
