[package]
name = "grid"
version = "0.1.0"

edition = "2024"
license-file.workspace = true

[dependencies]
app = { path = "../app" }
auth-domain = { path = "../auth-domain" }
domain = { path = "../domain" }
grid-endpoints = { path = "../grid-endpoints" }
grid-state = { path = "../grid-state" }

leptos.workspace = true
leptos_axum.workspace = true
leptos_router.workspace = true

tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [ "env-filter", "json" ] }

axum.workspace = true
axum-htmx = "0.8.1"
axum-login.workspace = true
http = { version = "1" }
http-body-util = { version = "0.1" }
tokio = { workspace = true, features = [ "rt-multi-thread", "macros", "signal" ] }
tower.workspace = true
tower-http = { workspace = true, features = [
  "trace",
  "compression-full",
  "request-id",
  "normalize-path",
] }
tower-sessions.workspace = true

miette = { workspace = true, features = [ "fancy" ] }
serde_urlencoded = "0.7.1"

[lints]
workspace = true
