
name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run:  docker load -i $(nix build ".#grid-container" -L --no-link --print-out-paths) && flyctl deploy --local-only --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
